### ISSUE TITLE
Issue with the knowledge check counter in case of element deletion

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#105]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
Knowledge check counter displayed on the course card doesn't get updated when deleting an element which contains knowledge checks. It will then correctly get updated once you add another knowledge check. Also, this issue doesn't occur if just deleting the knowledge check by itself. 

## Steps to Reproduce
1. Create a course and an element inside that course
2. Within that element create 2 Knowledge checks
3. Notice on the Course card the knowledge check counter is correct(shows 2)
4. Delete the element containing those knowledge checks
5. Notice the knowledge check counter is still displaying "2".

**Comment by underscope** [comment]
Feature has been removed
