### ISSUE TITLE
Text overflow issue in case of long Course description (with no spaces)

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#11]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
An overflowing issue occurs when typing a long Course description with no spaces as displayed in the screenshot below

![overflowing issue tailor](https://user-images.githubusercontent.com/34127147/37455537-9a907060-283d-11e8-9750-df5f14d64886.png)

**Comment by vladimyr** [comment]
@lbebic Btw, it is not related to this one but while we are here, is character limit respected? 🤔

**Comment by kjuej** [comment]
@vladimyr Yes, the character limit of 2000 is respected.
