### ISSUE TITLE
Able to set an exam group time limit to a negative number

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#138]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
Exam group time limit can be set to negative.

## Steps to Reproduce
1. Create an activity which can contain exams.
2. Edit that activity and add an exam group
3. Notice in the exam group you can set the time limit to a negative number

![screen shot 2018-11-29 at 09 49 25](https://user-images.githubusercontent.com/34127147/49209939-25e58480-f3bc-11e8-8ec2-25be437bebf6.png)

**Comment by zcuric** [comment]
@kjuej can you check this is is still an issue?

**Comment by kjuej** [comment]
@zcuric There's validation for this now:
<img width="326" alt="Screen Shot 2020-08-27 at 16 10 02" src="https://user-images.githubusercontent.com/34127147/91453331-e04f3780-e87f-11ea-977e-7a7f5cae3a71.png">
Unless we want to disable the ability for the spinner to go below 0?

Note: It's fine for the user to type a negative number and the validation saying it's not valid, but when clicking the down chevron, the value goes to negative.
