### ISSUE TITLE
Add Content element Space

### ISSUE THREAD

**Issue by markolovric** [ExtensionEngine/tailor#159]
## I'm submitting a...

- [ ] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Feature request
- [ ] Documentation issue or request

## Context
It would be nice to have an Content element "Space" that presents space between other content elements

![image](https://user-images.githubusercontent.com/41724080/50284400-350aa000-0459-11e9-94dc-602c0a1dbe2d.png)

**Comment by underscope** [comment]
I believe this is the same thing as 'page break' element

**Comment by markolovric** [comment]
Yes, I think page break came after this feature request.
