### ISSUE TITLE
Indent child elements

### ISSUE THREAD

**Issue by markolovric** [ExtensionEngine/tailor#162]
## I'm submitting a...

- [ ] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Feature request
- [ ] Documentation issue or request

## Context
It would be good to indent child elements inside multiselector for creating new activity elements.

## Expected Behavior
Every child element is indented in relation to parent

## Current Behavior
All elements are on the same level

![image](https://user-images.githubusercontent.com/41724080/51038768-5c661000-15b4-11e9-83d6-c4ca02ae454a.png)

**Comment by underscope** [comment]
Resolved
