### ISSUE TITLE
Allow publishing multiple activities at once

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#163]
## I'm submitting a...

- [ ] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Feature request
- [ ] Documentation issue or request

## Context
When publishing an activity, it would be nice if i had the ability to publish all child elements of that activity as well. A publish all button for publishing all activities within a course would be helpful as well.

**Comment by underscope** [comment]
Available in `3.0`
