### ISSUE TITLE
Teaching element icons displayed vertically instead of horizontally

### ISSUE THREAD

**Issue by ilijaveselica** [ExtensionEngine/tailor#164]
## I'm submitting a...
- [x] Bug report
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
When 5 (or 7) teaching element icons are displayed (when clicking on `+` button) then they are displayed vertically instead of horizontally.

## Steps to Reproduce
1. In `activities-rc.json` file enable 5 teaching elements inside `contentContainers.types`
2. Go in the app, edit any activity and click on `+` button

**Comment by vladimyr** [comment]
@ilijaveselica As a future reference:
Please use https://help.github.com/articles/closing-issues-using-keywords/ that would link your PR #165 to this issue automatically.
