### ISSUE TITLE
Disable Publish button while inputing

### ISSUE THREAD

**Issue by markolovric** [ExtensionEngine/tailor#169]
## I'm submitting a...

- [ ] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Feature request
- [ ] Documentation issue or request

## Context
Disable publish button (and other action buttons, if they are available) before input fields are closed / saved.

## Screnshoot
![image](https://user-images.githubusercontent.com/41724080/52277827-e60bc200-2955-11e9-8d40-138fc988d0db.png)

**Comment by underscope** [comment]
Publish is now (`3.0`) a dropdown and there is a confirmation modal so it feels like you can't run into problems anymore with changed meta that didn't get published.
