### ISSUE TITLE
Handle issues regarding JWT token

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#184]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
Token is still valid after expiration.
Multiple users can use the same token. 
JWT token exceeds 256 characters and may be cut-off from certain email service providers.

**Comment by ttokic** [comment]
Is this issue still reproducible? @underscope @vladimyr @kjuej 
I think @lukasaric added the Token validation just few months after this issue was reported.

**Comment by underscope** [comment]
@kjuej ?

**Comment by kjuej** [comment]
Seems to be working now, closing.
