### ISSUE TITLE
Add an indicator for "Fill in the blank" reflection which shows the number of blanks

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#207]
## I'm submitting a...

- [ ] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Feature request
- [ ] Documentation issue or request

## Context
Add a counter or preview so editors can easily identify how many blank spaces will be present for the reflection.

**Comment by underscope** [comment]
@kjuej Can you please note where would you like to add the counter. Thanks!

**Comment by kjuej** [comment]
@underscope Seems good the way it is now. Please close if no further updates are required.
