### ISSUE TITLE
Hardcoded values in Create content repository modal

### ISSUE THREAD

**Issue by kotky** [ExtensionEngine/tailor#21]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

I am seeing hardcoded values "Example Schema 1" and "Example Schema 2" in Create content repository modal after modifying  .activities-rc.json, I saw that it merges my config with defaults, shouldn't it choose my custom config over hardcoded default values? I am using develop branch.

**Comment by underscope** [comment]
Hi Josip,

Please try again with latest `develop`. Keep in mind that in order to use seed you need those schemas exposed (And you can do that via `ENABLE_SEED_SCHEMA` setting)

Cheers 🍺
