### ISSUE TITLE
Feature for adding images inside text content type

### ISSUE THREAD

**Issue by askoric** [ExtensionEngine/tailor#3]
![screen shot 2018-03-12 at 3 52 48 pm](https://user-images.githubusercontent.com/638251/37290786-79b0a0fe-260d-11e8-87c0-bf93d8d7aa58.png)

**Comment by underscope** [comment]
Possible solutions

https://github.com/quilljs/quill/issues/863
https://github.com/quilljs/quill/issues/1089
