### ISSUE TITLE
Navigation between activities inside the repository

### ISSUE THREAD

**Issue by markolovric** [ExtensionEngine/tailor#363]
## I'm submitting a...

- [ ] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Feature request
- [ ] Documentation issue or request

## Context
It would be nice to have a button or arrow inside activity page to navigate to next or previous activity inside the whole repository

**Comment by underscope** [comment]
@markolovric Resolved with activity navigation
