### ISSUE TITLE
Specific issue with progress icon on file upload meta component

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#383]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Steps to Reproduce

1. Try to add a file with invalid(not supported) extension to file upload.
2. Click on add file again and then click cancel when selecting a file - Notice infinite circular progress icon is displayed

<img width="1327" alt="Screen Shot 2019-11-15 at 13 42 00" src="https://user-images.githubusercontent.com/34127147/68944319-dd320180-07ad-11ea-85bf-7ceb1de68e72.png">

**Comment by underscope** [comment]
@kjuej This one should no longer be applicable
