### ISSUE TITLE
Assessment position not assigned upon publish

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#388]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
When publishing an element containing assessments, the assessment position is null.

![Screen Shot 2019-11-15 at 14 11 18](https://user-images.githubusercontent.com/34127147/68945954-f472ee00-07b1-11ea-94ba-d81b96515251.png)

**Comment by underscope** [comment]
Assessment pool does support position at the moment. I will remove attr to avoid confusion.

**Comment by underscope** [comment]
Custom container. N/A
