### ISSUE TITLE
Validation issue occurs on any input

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#389]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
Validation errors shown in console if you try to save the input too fast.

<img width="1077" alt="Screen Shot 2019-11-15 at 14 26 52" src="https://user-images.githubusercontent.com/34127147/68947330-76b0e180-07b5-11ea-96ab-2518052fa156.png">

**Comment by underscope** [comment]
@kjuej Should be resolved on the latest develop
