### ISSUE TITLE
BUG: No preview image for uploaded image inside teaching teaching element

### ISSUE THREAD

**Issue by askoric** [ExtensionEngine/tailor#39]
For a teaching element of type "IMAGE", there is a display bug;
Preview image is not present. The preview image was present at upload time.
Upon re-entering the content container, the preview image is absent.
The image url *is* present in the corresponding json file (published) and *is* present is /assets/ folder.
The src= is *absent* in the preview image <img tag.

<img width="683" alt="screen shot 2018-03-26 at 1 46 09 pm" src="https://user-images.githubusercontent.com/638251/37904673-c88cc8a2-30fc-11e8-83c1-6c1150302981.png">
![screen shot 2018-03-26 at 1 42 58 pm](https://user-images.githubusercontent.com/638251/37904830-302c7c14-30fd-11e8-9069-49ff73d7f86b.png)

**Comment by underscope** [comment]
Configuration issue 🐛
