### ISSUE TITLE
Vuetify issue on login page

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#392]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
(Please see the screenshot below)
Notice the console error.
Notice the text overlap with label in email and password text fields.

<img width="1277" alt="Screen Shot 2019-11-18 at 13 04 59" src="https://user-images.githubusercontent.com/34127147/69051323-48751100-0a04-11ea-8c54-cd661d9a6ba5.png">

**Comment by underscope** [comment]
@kjuej Resolved on latest develop
