### ISSUE TITLE
No border for some buttons/text fields in the project

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#393]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
Button border missing for:
1. Video component control buttons
2. Deletion confirmation modal
3. PDF control button
4. Answer feedback (text field)
5. Toggle all button in course structure

<img width="1011" alt="Screen Shot 2019-11-18 at 14 34 11" src="https://user-images.githubusercontent.com/34127147/69056937-44032500-0a11-11ea-9bac-6a85341121b4.png">

<img width="690" alt="Screen Shot 2019-11-18 at 14 38 18" src="https://user-images.githubusercontent.com/34127147/69056903-35b50900-0a11-11ea-96a7-e958502626d9.png">

<img width="921" alt="Screen Shot 2019-11-18 at 14 37 59" src="https://user-images.githubusercontent.com/34127147/69056915-3baaea00-0a11-11ea-8409-03eff2accf1b.png">

<img width="819" alt="Screen Shot 2019-11-18 at 14 43 09" src="https://user-images.githubusercontent.com/34127147/69057264-d4416a00-0a11-11ea-9f53-624110c41569.png">

**Comment by underscope** [comment]
We are going to use more text (without outline) version of btn
