### ISSUE TITLE
Unnecessary left padding for meta select

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#394]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
<img width="492" alt="Screen Shot 2019-11-18 at 14 41 03" src="https://user-images.githubusercontent.com/34127147/69057131-9c3a2700-0a11-11ea-9b6a-dff180ff6ff6.png">

**Comment by underscope** [comment]
@kjuej This one is resolved with new select ? If so please close it.
