### ISSUE TITLE
Minor issue regarding container element creation

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#398]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Steps to Reproduce
1. Create a course
2. Create an element in a course
3. Click on that element to show sub-level creation menu ("Create" "Copy" "Cancel" buttons)
4. Click on Create or Copy to show additional creation details
5. Close the creation menu by clicking the same button as on step 2
6. Open the creation menu again and notice the the additional creation detail menu is shown instead of the basic menu as on step 3

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/34127147/69235188-2066e880-0b91-11ea-918c-5b87bacdd55e.gif)

**Comment by underscope** [comment]
@kjuej N/A anymore
