### ISSUE TITLE
Unable to create new user on tailor

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#401]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
Server error when creating a new user on tailor

<img width="1550" alt="Screen Shot 2019-11-27 at 12 08 49" src="https://user-images.githubusercontent.com/34127147/69718452-b0b3a900-110e-11ea-891d-9adb0db849c8.png">

**Comment by underscope** [comment]
@kjuej Please check if this is still a problem on develop. I was unable to reproduce.

**Comment by kjuej** [comment]
@underscope Seems like the issue no longer occurs.
