### ISSUE TITLE
Repository unavailable to admins after archiving course creator

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#441]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
After archiving an admin user, all repositories created by him are now unavailable to all other admin users

## Steps to Reproduce
1. Create a new admin user
2. Login with that admin user and create a repository
3. Logout with that user and archive him/her
4. Notice after doing so, the course created on step 2 is no longer visible to all other admin users

<img width="1510" alt="Screen Shot 2020-02-07 at 13 40 16" src="https://user-images.githubusercontent.com/34127147/74030455-645ad400-49af-11ea-8329-8af65a2c8cf2.png">

**Comment by underscope** [comment]
@kjuej This one seems no longer applicable. Let me know of you can reproduce it.

**Comment by kjuej** [comment]
@underscope It is no longer applicable.
