### ISSUE TITLE
Vee-validate error in console when adding typing in a new tag 

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#467]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

<img width="1481" alt="Screen Shot 2020-03-27 at 10 13 35" src="https://user-images.githubusercontent.com/34127147/77740570-c92bc580-7013-11ea-89e7-a44767f695a1.png">

**Comment by underscope** [comment]
@kjuej Should be resolved on the latest develop
