### ISSUE TITLE
Remove unnecessary left padding when linking objectives to exams

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#483]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context

<img width="785" alt="Screen Shot 2020-04-09 at 09 49 55" src="https://user-images.githubusercontent.com/34127147/78871163-963bf580-7a47-11ea-9d42-ec1a0a1e5944.png">

**Comment by underscope** [comment]
@kjuej Should be good in the latest version
