### ISSUE TITLE
Frontend issue when deleting a repository

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#484]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
When deleting a repository, you're redirected to the catalog page where you can see the repo you've deleted (it's not removed on frontend).

**Comment by underscope** [comment]
@kjuej This one should be resolved (latest develop)
