### ISSUE TITLE
Carousel element has fixed height and is not scrollable

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#494]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
Since the element is not scrollable, when you add multiple element to a single carousel slide, the last element is never fully visible.
<img width="823" alt="Screen Shot 2020-04-23 at 16 22 37" src="https://user-images.githubusercontent.com/34127147/80110308-d38f9f80-857e-11ea-864d-84e96e67212f.png">

**Comment by kjuej** [comment]
@underscope Still unable to edit carousel height.

**Comment by underscope** [comment]
Update context / open new issue since this one is focused around element not being scrollable and does not mention height editing ;)
