### ISSUE TITLE
Minor issue with removing tags when repositories are filtered by tags

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#503]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
When removing a tag on a set of filtered repositories (filtered by tag), the repository which has its tag removed doesn't get removed from the filter:

<img width="1166" alt="Screen Shot 2020-04-30 at 12 28 28" src="https://user-images.githubusercontent.com/34127147/80700633-56b07880-8ade-11ea-91c7-668fe6e56eb3.png">
Notice the last repository has no tags, yet it's still displayed on the list

**Comment by underscope** [comment]
@kjuej This one should be resolved on the latest develop
