### ISSUE TITLE
Issue when adding an element on graph view page

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#508]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
When adding an element on graph view page, the element doesn't appear on the front end initially(notice the error in the console)

<img width="1449" alt="Screen Shot 2020-05-12 at 10 08 14" src="https://user-images.githubusercontent.com/34127147/81658037-b68d1480-9438-11ea-8a7e-554d15f204b5.png">

**Comment by underscope** [comment]
@kjuej I believe that this one has been addressed. Please reopen if the issue still exists.
