### ISSUE TITLE
Able to add empty assessment element

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#513]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
I can add an empty assessment element, by just selecting it in the menu and refreshing the page with no input:

<img width="1230" alt="Screen Shot 2020-05-14 at 12 24 13" src="https://user-images.githubusercontent.com/34127147/81923412-eb869c00-95dd-11ea-8a14-50c2c50a5a0d.png">

**Comment by underscope** [comment]
@kjuej It is the expected behavior within the standard container (ability to add a placeholder, just like for any other element) 😉
