### ISSUE TITLE
Change validation error message for numerical response assessment

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#515]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
Should an error message saying "Only numerical input allowed, if decimal number is needed please use . to separate numbers (e.g. '3.14')." be displayed in case the user hasn't given any response?
<img width="799" alt="Screen Shot 2020-05-15 at 16 22 29" src="https://user-images.githubusercontent.com/34127147/82061037-79d74c80-96c8-11ea-89a6-739ab97d8319.png">

**Comment by underscope** [comment]
@kjuej Will update message (for now) to be a bit more generic (until we introduce vee-validate for all assessments).
