### ISSUE TITLE
As a User, I should receive activity link within discussion notification

### ISSUE THREAD

**Issue by underscope** [ExtensionEngine/tailor#516]
## I'm submitting a...
- [ ] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Feature request
- [ ] Documentation issue or request

## Context
Upon posting a comment within the discussion section, users which are added to the repository should receive email notification. Include the link to the related activity (activity selection/focus via activityId query param is already in place; i.e. `/#/repository/11/?activityId=169`).

**Comment by markolovric** [comment]
1. Regarding information inside the Activity card on Board Page, what informations are needed?
I was thinking about Activity type, Activity name, Assignment, Priority, Time Estimate, and icon to open the Activity Page. Is this enough?

2. How many status columns are needed? TO DO, IN PROGRESS, QA, and DONE?

![image](https://user-images.githubusercontent.com/41724080/82549257-f18bf800-9b5c-11ea-8c3c-23ef4fcc3368.png)

**Comment by markolovric** [comment]
Inside Activity Card maybe also to add circle with publish status?

**Comment by underscope** [comment]
Wrong issue ;)

**Comment by hrvojevu** [comment]
> Wrong issue ;)

@underscope is this issue still relevant? This comment confuses me 😄

**Comment by markolovric** [comment]
@hrvojevu yes it is, @underscope commented this to me, I added a comment to the wrong issue and deleted it after realizing
