### ISSUE TITLE
As a User, I should be able to define workflow for repository and manage activity state

### ISSUE THREAD

**Issue by underscope** [ExtensionEngine/tailor#518]
## I'm submitting a...

- [ ] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Feature request
- [ ] Documentation issue or request

## Context
Content creators should be able to define custom workflow (similar to JIRA; can be config based initially like repository structure) and manage activity state (i.e. TO DO, IN PROGRESS, DONE).

- Within the activity sidebar and editor, User should be able to see and change the current state
- All state changes should be tracked
- As a User, I should be able to assign the activity to a particular User
- As an Assigned User, I should receive a notification
- There should be an additional page/dashboard with the listing of all activities, information regarding status and filtering by id, name, status, and assignee

**Comment by markolovric** [comment]
I will make some designs.

**Comment by markolovric** [comment]
1. Regarding information inside the Activity card on Board Page, what informations are needed?
I was thinking about Activity type, Activity name, Assignment, Priority, Time Estimate, and icon to open the Activity Page. Also to add circle with publish status, same as is on Repository card (not in this screenahot). Is this enough?

2. How many status columns are needed? TO DO, IN PROGRESS, QA, and DONE?

![82549257-f18bf800-9b5c-11ea-8c3c-23ef4fcc3368](https://user-images.githubusercontent.com/41724080/82562035-bd243600-9b74-11ea-812c-3ad56645ef61.png)

**Comment by underscope** [comment]
1. Seems enough to me for the first iterarion
2. Workflow should be configurable, so there might be N columns.

Consider tweaking UI a bit more to look a bit more unique / less JIRA alike.

**Comment by underscope** [comment]
Don't forget the sidebar as well 😉 We need status select, assignment, and priority.
