### ISSUE TITLE
Issue with re-ordering html component after changing the tes meta

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#538]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Steps to Reproduce

1. Create a HTML component with tes meta
2. Add/change HTML component's tes meta
3. reorder the HTML component a couple of times, and notice the HTML element gets populated with strings as shown in the screenshot below

<img width="1658" alt="Screen Shot 2020-05-26 at 14 08 19" src="https://user-images.githubusercontent.com/34127147/82899063-9ee67d80-9f5a-11ea-967a-e6be2b6adb28.png">

**Comment by markolovric** [comment]
@kronicker worked on this

**Comment by markolovric** [comment]
@kronicker what is the update of this issue? Would it be merged to develop/master?

**Comment by kjuej** [comment]
This is an issue with a specific scheme, not tailor.
