### ISSUE TITLE
Element toolbar missing in specific scenario

### ISSUE THREAD

**Issue by mbareta** [ExtensionEngine/tailor#557]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
Reproduced in Tailor v4.0.0 release on a live server (production build).
* Operating System: MacOS
* Browser: Chrome

## Expected Behavior
Clicking on an element should activate the element toolbar.

## Current Behavior
The toolbar is not activated.

## Steps to Reproduce
[Watch this video](https://drive.google.com/file/d/1x47L2jh55sMVFT2JhmYhaoSCozDitiQK/view?usp=sharing)
1. add new activity from the "Structure" view
2. open any other activity
3. from the left hand nav, navigate to the new activity
4. add an element that has a toolbar
5. notice that toolbar is not activated
6. change page and come back and the toolbar works as expected

**Comment by zcuric** [comment]
@underscope @vladimyr EventBus is causing some issues, I think. 
For example: https://github.com/ExtensionEngine/tailor/blob/develop/client/components/common/tce-core/ContentElement.vue#L61 
`this.id` is always undefined.

**Comment by zcuric** [comment]
Also, when created in this specific way, element is not focusable, i.e. it's not set as focusedElement in ActivityContent component..
