### ISSUE TITLE
Visual issue when creating a new repository

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#575]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
When creating a new repository, immediately after clicking the create button the repository type will show the type of the first repository on the list:
![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/34127147/89790824-cc3ad480-db22-11ea-91ec-6223d088e523.gif)

**Comment by underscope** [comment]
@zcuric if you close modal with error, now the error is going to be visible. The problem is that we need modal on close / not visible event and handling.

**Comment by kjuej** [comment]
@underscope Issue no longer occurs.
