### ISSUE TITLE
Save issue when creating an assessment in an assessment group

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#588]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
When creating an assessment in an assessment group (multiple assessments in an exam), save button needs to be clicked twice for the assessment to be saved.

**Comment by kjuej** [comment]
@zcuric This creates issues when adding normal assessments as content:
1. They're automatically saved upon adding, instead of being added in edit mode
2. When you add an answer they automatically get saved again

**Comment by underscope** [comment]
Resolved on the latest develop
