### ISSUE TITLE
Item elements not sorted as they should be(when using add element below)

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#596]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
When using "add element below" feature, the element first gets positioned at the very bottom, then after page refresh gets positioned at the top.
![CopyBelowTailor](https://user-images.githubusercontent.com/34127147/94794970-f9965700-03dc-11eb-8efc-4682187f202b.gif)

**Comment by kjuej** [comment]
The issue seems to occur when inserting element in-between copied elements.

**Comment by underscope** [comment]
@hrvojevu ^
