### ISSUE TITLE
PDF download automatically starts upon viewing content container

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#600]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
Uploaded pdf element automatically starts download upon refreshing the content container.
![TailorPDF](https://user-images.githubusercontent.com/34127147/94016747-d05b4280-fdae-11ea-9926-cc9890c6b7ba.gif)

**Comment by underscope** [comment]
@kjuej Unable to reproduce, seems like you have some err on that one, can you record the full flow?

**Comment by kjuej** [comment]
@underscope Can't seem to reproduce it as well. I'll keep it open for a few days to see if i can make it happen again.

**Comment by kjuej** [comment]
@underscope Seems like an issue occurred when the pdf element wasn't uploaded well (pdf was showing errors), upon re-upload, the issue no longer occurred.
