### ISSUE TITLE
Should I be able to remove myself as a repository admin?

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#601]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
The creator of the admin can remove himself as the admin in repository settings.
<img width="1404" alt="Screen Shot 2020-09-29 at 15 50 55" src="https://user-images.githubusercontent.com/34127147/94567290-95a05100-026b-11eb-9595-e13269618f65.png">

**Comment by underscope** [comment]
Being a platform admin or only repository admin? (this might be a way to stop the notifications)

**Comment by kjuej** [comment]
@underscope It makes sense if this stops the notifications, didn't think about it that way.
