### ISSUE TITLE
Able to publish deleted elements in a specific scenario

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#602]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
If you have 2 tailor instances running and delete a repository element in once instance, you may publish that element on the other instance if you haven't refreshed the page yet.

## Steps to Reproduce
1. Create a repository
2. Add a couple of elements in that repository
3. Publish the entire repository
4. Open tailor instance in another tab and enter that repository
5. Delete an element in the first tab (the element is no longer shown in the bucket)
6. Notice you can still publish that element in the other tab.

**Comment by underscope** [comment]
@kjuej Resolved on the latest `develop`?

**Comment by kjuej** [comment]
@underscope Seems the issue can no longer occur when SSE was added for element creation.
