### ISSUE TITLE
Element link improvements 

### ISSUE THREAD

**Issue by bubafinder** [ExtensionEngine/tailor#628]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request
- [x] Improvement

## Improvement

After some time using the Element link feature, there are few improvements to suggest
1. Make sticky footer in Select Element dialog
![image](https://user-images.githubusercontent.com/41724080/96007320-aa214380-0e3e-11eb-8e06-6c3ebf6af15f.png)

2. When selecting an element inside the Select Element dialog, it would be awesome if there were an indication of the activity types, use existing color coding for activities from the repository.
![image](https://user-images.githubusercontent.com/41724080/96007790-287de580-0e3f-11eb-9bd7-089ce01766cf.png)

3. Content authors are getting confused when a link has already been added and think they can add more links. Remove the edit icon from the Element sidebar and put the eye icon which will present that the user can only view the selected link and if they need to edit it or remove, they can do it by clicking the x icon.
![image](https://user-images.githubusercontent.com/41724080/96008818-3b44ea00-0e40-11eb-9743-d066a0ea8829.png)

## Bug report

1. The order of elements inside the Select Element dialog is not correct, not as inside the related Activity
![image](https://user-images.githubusercontent.com/41724080/96007618-f076a280-0e3e-11eb-8f4b-dbdbb5021312.png)

**Comment by underscope** [comment]
@mcapeta

**Comment by bubafinder** [comment]
One comment from @kronicker on the bug from this issue

> I think it’s due to the way Tailor orders elements. Since we have an extra layer i.e. subcontainers in custom container we have multiple elements with same position in one container (since they’re deeply nested under subcontainers) for which Tailor cannot account for.

**Comment by mcapeta** [comment]
@markolovric Moving suggestion 2 to separate issue since both reported bug and improvement 1 are resolved within #624 and improvement 3 is not an issue as we've already discussed?
