### ISSUE TITLE
Course name can overlap with course description

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#63]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
In case of a longer Course name and description an text overlap issue occurs
![screen shot 2018-03-30 at 11 02 37](https://user-images.githubusercontent.com/34127147/38132221-77be7c8e-340a-11e8-8efc-8ced95e542a1.png)

**Comment by underscope** [comment]
Can you please re-check this and provide exact input + browser info.

**Comment by kjuej** [comment]
Unable to reproduce. Probably a side effect of another issue.
