### ISSUE TITLE
Minor UI improvements

### ISSUE THREAD

**Issue by bubafinder** [ExtensionEngine/tailor#656]
## I'm submitting a...

- [ ] Bug report  
- [x] Improvements
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Minor UI improvements 

1. Improve the hover background contrast for icons on the right side of the search input
![image](https://user-images.githubusercontent.com/41724080/97878783-5e680880-1d1f-11eb-9066-f3560fbdb1ab.png)

2. Improve the hover background contrast for the 'Open settings' icon in the repository card
![image](https://user-images.githubusercontent.com/41724080/97880359-5e690800-1d21-11eb-9be1-741da20ef6be.png)

3. Order tags by name in tag dropdown
![image](https://user-images.githubusercontent.com/41724080/97880834-ebac5c80-1d21-11eb-928c-771466a33f86.png)

4. Add selected style for searched Activity item
![image](https://user-images.githubusercontent.com/41724080/97880947-10083900-1d22-11eb-9116-cb6ff65b0ccc.png)

5. Improve Activity background color/contrast for default and hover/selected state
![image](https://user-images.githubusercontent.com/41724080/97881642-f1567200-1d22-11eb-8da8-a092835c6fc1.png)

6. Improve the hover style of the repository card. Only 'Edited [time] by [user]' text is changed in the card (bolded). Maybe to change the weight of the title as well? This is still open for discussion
![image](https://user-images.githubusercontent.com/41724080/97995380-b9186780-1de6-11eb-931f-ef799cb99c06.png)

7. Also opened for discussion. Because the date format is M/D/Y, remove the 24-hours clock and ad AM/PM to the time format. Please make sure that the same date&time format is used on the whole platform.
![image](https://user-images.githubusercontent.com/41724080/97997015-cb93a080-1de8-11eb-8c6a-70506e7ddbdb.png)

**Comment by underscope** [comment]
@markolovric Closing this one, please reopen new one for the next milestone with remaining requests (two separate tickets)
