### ISSUE TITLE
Comment improvements 

### ISSUE THREAD

**Issue by bubafinder** [ExtensionEngine/tailor#657]
## I'm submitting a...

- [ ] Bug report  
- [x] Improvements
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Comment improvements 

1. Remove all newlines and spaces if they are at the end of the comment
![image](https://user-images.githubusercontent.com/41724080/97881900-45615680-1d23-11eb-9530-f78ccca360b4.png)

2. After the user receives an email for the user comment and clicks on the View button, scroll to the related comment on the opened page
![image](https://user-images.githubusercontent.com/41724080/97882415-e2bc8a80-1d23-11eb-8d87-d8387f609583.png)

3. Add Activity name at the end of the email Title to make emails better grouped
![image](https://user-images.githubusercontent.com/41724080/97882778-48107b80-1d24-11eb-86bc-e3de32055574.png)

4. Send an email after editing the comment
![image](https://user-images.githubusercontent.com/41724080/97882860-670f0d80-1d24-11eb-980b-cfb11a94bd16.png)

5. Add 'Date - Time' tooltip for hovering Comment Time
![image](https://user-images.githubusercontent.com/41724080/97882949-8443dc00-1d24-11eb-9271-82b2603a3af1.png)

**Comment by underscope** [comment]
@borna223 This is targeted for 6 milestone 😉

**Comment by markolovric** [comment]
@borna223 
A lot of errors in console

![image](https://user-images.githubusercontent.com/41724080/99363198-bde41d80-28b4-11eb-9207-265ba4fc713e.png)
