### ISSUE TITLE
Improve element drag and drop feature

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#699]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
It's currently quite hard to drag and drop and element between elements that are not in your current field of view:
![DragAndDrop](https://user-images.githubusercontent.com/34127147/101489837-cda9cb80-3961-11eb-80a6-e9d2cec70ca7.gif)

**Comment by bubafinder** [comment]
Also, add a visual representation of the drop area, something like in Trello

![image](https://user-images.githubusercontent.com/41724080/101490325-7a844880-3962-11eb-8a49-f4e2b0d1066f.png)

**Comment by hrvojevu** [comment]
Closing due to linked PR being merged.
