### ISSUE TITLE
Weird behavior on Comment menu

### ISSUE THREAD

**Issue by bubafinder** [ExtensionEngine/tailor#732]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
The comment menu is opening and closing after hovering above the comment surface. After submitting the comment, everything behaves correctly.
Video attached.

https://user-images.githubusercontent.com/41724080/107240747-8e176280-6a2a-11eb-9efe-58caabeff72b.mp4

**Comment by underscope** [comment]
@lukasaric ?

**Comment by lukasaric** [comment]
Cannot reproduce. @markolovric can you reconfirm the issue?

**Comment by bubafinder** [comment]
@lukasaric Still active on Perspective container in Sample scheme.

**Comment by zcuric** [comment]
@markolovric I've checked also, cannot reproduces.

**Comment by bubafinder** [comment]
Not active on the beta dev server
