### ISSUE TITLE
Repository card is not clickable in its whole area

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#734]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
Unable to open the repository by clicking anywhere on the repository card (try clicking below the Repo name / admin name)
![RepoCardIssue](https://user-images.githubusercontent.com/34127147/107377725-8f5c9400-6aeb-11eb-924b-5e5d54100e55.gif)

**Comment by underscope** [comment]
@kjuej Please revisit on latest develop
