### ISSUE TITLE
Issue with editing repository settings

### ISSUE THREAD

**Issue by underscope** [ExtensionEngine/tailor#740]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
If super admin is not added to the repository he is not able to edit repository meta (i.e. name).

**Comment by kronicker** [comment]
As far as I can reproduce this occurs only when you land directly on the repo settings page w/o going through the catalog first.
