### ISSUE TITLE
Tag colors are changed, not accessible

### ISSUE THREAD

**Issue by bubafinder** [ExtensionEngine/tailor#743]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
The text inside the tag is not readable. Screenshot attached

![image](https://user-images.githubusercontent.com/41724080/107769474-58c78900-6d38-11eb-8c7e-22b08cb626a1.png)

**Comment by underscope** [comment]
@markolovric Resolved on the latest develop
