### ISSUE TITLE
Two Content elements created by opening the newly created Activity element

### ISSUE THREAD

**Issue by bubafinder** [ExtensionEngine/tailor#772]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
Env: dev server https://beta.tailor.extnsn.com/
1. Create an empty Sample repository
2. Create a new Topic element
3. Open newly created Topic element

Issue: Go to the History page for the related repository and notice that the Perspective container and Assessment pool are created by opening the element.

<img src="https://user-images.githubusercontent.com/41724080/110444918-de332480-80bd-11eb-8e58-899a270f0933.png" width="400px">

**Comment by bubafinder** [comment]
@underscope please confirm if this is a bug?

**Comment by underscope** [comment]
@markolovric This is not a bug. Long time ago, for sake of simpler UI, we added autogeneration of content containers upon opening the activity within editor (Sometimes this process is manual, sometimes automatic; we need to improve at some point messaging within revision list by adding a context).
