### ISSUE TITLE
Server not working on node v13

### ISSUE THREAD

**Issue by mandryllo** [ExtensionEngine/tailor#794]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
The server is not working on early v13.x node versions 

* node version: v13.1.0
* npm version: v6.12.1

## Failure Information (for bugs)
This is due to [openid-client](https://github.com/panva/node-openid-client) doesn't support these versions.
As stated [here](https://github.com/panva/node-openid-client/blob/main/CHANGELOG.md#-breaking-changes) 
`due to added ESM module support Node.js version with ESM implementation bugs are no longer supported, this only affects early v13.x versions. The resulting Node.js semver range is ^10.19.0 || >=12.0.0 < 13 || >=13.7.0 (also taking into account the got dependency update)
`

![Screen Shot 2021-03-24 at 1 01 54 PM](https://user-images.githubusercontent.com/10136836/112307429-36af1800-8ca1-11eb-958a-c867d92e5f4a.png)

**Comment by bubafinder** [comment]
Closing because the node is bumped to the v20.
