### ISSUE TITLE
Disable adding repository with an already used name

### ISSUE THREAD

**Issue by bubafinder** [ExtensionEngine/tailor#805]
## I'm submitting a...

- [ ] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request
- [x] Enhancement 

## Context
1. Go to the Catalog page
2. Try to add the repository with an already used name

The user can add the repository with an already used name. Introduce a warning message to the User that a Course with that name already exists.

![image](https://user-images.githubusercontent.com/41724080/113130042-e5140980-921b-11eb-8bee-49f273f5125e.png)

**Comment by underscope** [comment]
Changing the label since it is intended behavior rather than an issue. Let's chat about it.

**Comment by bubafinder** [comment]
Adding @Amer21214 to the discussion.

**Comment by Amer21214** [comment]
If we will allow new Courses to be created with the name of a pre-existing Course, I really do suggest we introduce a warning message/validation to the User that a Course with that name already exists. The benefit of this action is worth the minor amount of work needed to implement specified behavior.

**Comment by lukasaric** [comment]
@markolovric @Amer21214  Should we display warning message on repository (course) settings details while user is editing repo name?

**Comment by Amer21214** [comment]
@malizeus - place it right underneath the repository name field, please.

**Comment by underscope** [comment]
@markolovric @Amer21214 Should this happen when the user does not see an existing repository (with the same name; due to not having access to it). Will it be confusing? 🤔

**Comment by bubafinder** [comment]
I think it should not be confusing. The user needs to know that there is a repository with a duplicate name. Also, I requested Luka to skip soft-deleted repositories.

**Comment by Amer21214** [comment]
@underscope I wasn't aware that there could be courses visible to one User and not to another User. The underlying goal here is to avoid having any User see 2 Courses with the same name. 
This, for instance, includes the case where any "sub-User" creates a Course with a name that exists in the Course List of another sub-User, but both Courses would be visible in the list to an Admin/Instructor.
