### ISSUE TITLE
Compact logo version used in emails instead of normal version as on Login page

### ISSUE THREAD

**Issue by bubafinder** [ExtensionEngine/tailor#807]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
Compact logo version used in emails instead of normal version as on Login page.

Email
<img src="https://user-images.githubusercontent.com/41724080/113136091-37a4f400-9223-11eb-990b-68bf20bbb178.png" width="400px">

Login page
<img src="https://user-images.githubusercontent.com/41724080/113136017-23f98d80-9223-11eb-99b8-6cb71c01c258.png" width="400px">

**Comment by underscope** [comment]
@markolovric That was actually on purpose 😉 (since it doesn't depend on the background / it looked consistently better to me)
