### ISSUE TITLE
Change the `People` tab to the `Manage access`

### ISSUE THREAD

**Issue by bubafinder** [ExtensionEngine/tailor#813]
## I'm submitting a...

- [ ] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request
- [x] Enhancement 

## Context
Change the `People` tab on Repository->Settings part to the `Manage access`. The benefit is a better understanding of the purpose to the end-users

<img src="https://user-images.githubusercontent.com/41724080/113294430-452bae00-92f7-11eb-919a-7faadd2b68e0.png" width="350px">

**Comment by underscope** [comment]
@markolovric Some of the big platforms like JIRA are simplifying this and naming it the same way 😉 Still want to rename it?

**Comment by bubafinder** [comment]
I think the change would be more understandable for users.
But we can ask @Amer21214 again.

**Comment by Amer21214** [comment]
@markolovric @underscope **JIRA**, **Github** and **Gmail** use **_People_**, so I'm ok with keeping it as **_People_**.
