### ISSUE TITLE
Half width element turns to full width after input

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#818]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
![HalfWidthIssue](https://user-images.githubusercontent.com/34127147/113690306-8b07be00-96cb-11eb-9f53-947e754b6d89.gif)

**Comment by underscope** [comment]
@malizeus  Please take a look as soon as you get a chance 😉

**Comment by kjuej** [comment]
@malizeus @underscope Issue seems to still occur on half width:
1. Image element
2. Deprecated html element
3. Embed element
