### ISSUE TITLE
Element toolbar stays open after switching to new activity

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#821]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
Notice when clicking an image element then switching the activity, the image element toolbar stays open.
![ToolbarIssue](https://user-images.githubusercontent.com/34127147/113999454-5a09c380-985a-11eb-83e4-66e9709659c8.gif)

**Comment by markolovric** [comment]
Looks good 👍
