### ISSUE TITLE
Relationships grouped by name

### ISSUE THREAD

**Issue by bubafinder** [ExtensionEngine/tailor#826]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
Relationships with the same name are grouped in the dropdown selection, which is causing the user is not sure which relationship to choose.

![image](https://user-images.githubusercontent.com/41724080/114718652-d2113700-9cfb-11eb-8c45-23f0bfb4231c.png)

**Comment by underscope** [comment]
@markolovric Would it make sense to prefix with id?

**Comment by bubafinder** [comment]
Definitely, it would be good to start use ID in some places 👍
