### ISSUE TITLE
Improve UI for adding items

### ISSUE THREAD

**Issue by marjev** [ExtensionEngine/tailor#83]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Expected Behavior
We should make it more prominent. Perhaps a solution would be to increase the contrast by changing the color of the horizontal line and the plus symbol.

## Current Behavior
<img width="976" alt="screen shot 2018-04-11 at 12 23 45 pm" src="https://user-images.githubusercontent.com/6833568/38611178-47182012-3d83-11e8-8ca5-26412dbc8ad6.png">

**Comment by markolovric** [comment]
![adding items](https://user-images.githubusercontent.com/41724080/50284343-10aec380-0459-11e9-9992-f1e26824444c.jpg)

![adding items - spaces](https://user-images.githubusercontent.com/41724080/50284351-15737780-0459-11e9-9244-ee0c650f2505.jpg)

**Comment by underscope** [comment]
Improved in `3.0`

![image](https://user-images.githubusercontent.com/6253820/56682921-ddad6280-66cc-11e9-8852-8f7f4199305c.png)
