### ISSUE TITLE
Upon filtering by user, additional border to user avatar is added

### ISSUE THREAD

**Issue by bubafinder** [ExtensionEngine/tailor#840]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
On the Progress (workflow) page, upon filtering by the user (clicking on user avatar), an additional border to the user avatar is added. Remove the inner border.

![image](https://user-images.githubusercontent.com/41724080/117112044-c4921e80-ad88-11eb-9977-148137c85ea8.png)

**Comment by MiroDojkic** [comment]
@markolovric @underscope I added this on purpose to create contrast between the colored border and avatar image. Do you think it's unnecessary?

**Comment by underscope** [comment]
@MiroDojkic Would it make sense to have it in the same color as the background? (similar to how JIRA approaches it).

**Comment by MiroDojkic** [comment]
@underscope sure, that's a good idea.
