### ISSUE TITLE
"...field is required" validation message prevents input

### ISSUE THREAD

**Issue by askoric** [ExtensionEngine/tailor#85]
## I'm submitting a...
- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context

<pre><code>
<u>For server issues</u>
* node version: 8.9.4
* npm version: 5.6.0

<u>For client issues</u>
* Operating System: macOS Sierra 10.12.6
* Browser: Google Chrome Version 65.0.3325.181 (Official Build) (64-bit)
</pre></code>

## Expected Behavior

An input that has failed validation should be focusable by a mouse click.

## Current Behavior

A required input field that has failed validation (was left blank) is not clickable. In other words, a user is unable to click on it to enter data. The widget is focusable using tab key though.

## Failure Information (for bugs)

![screen shot 2018-04-12 at 2 52 26 pm](https://user-images.githubusercontent.com/638251/38679418-faeff368-3e63-11e8-9c26-842d3be55cc7.png)

## Steps to Reproduce

1. Have a required metadata field of type "INPUT" in your repo schema.
2. Click on the field and then click away to fail the front-end validation. Get the  "The xxx field is required." error message.
3. Click on the field to attempt to enter data into it. The cursor does not appear.

## Failure Logs

<pre><code>
* Server log: none
* Browser console log: none
</pre></code>

**Comment by underscope** [comment]
I believe this issue was fixed on `develop` a long time ago, it just needs to be merged into master. Can you please test on develop and let me know if you still have problems.

Thanks!

**Comment by askoric** [comment]
Tested on `develop` and confirmed fixed.
